本文原文地址在[[http://doc.norang.ca/org-mode.html][Org Mode - Organize Your Life In Plain Text!]]
* 4 入门
:PROPERTIES:
:ID:       e50cfa7b-a1be-4897-9c7c-8c669b42a4d2
:END:
入门 =org-mode= 真的很容易。你只需要在你的Emacs启动文件中加入几行，就可以使用来自git仓库的最新版本的org-mode。
** 4.1 用git获取org-mode
:PROPERTIES:
:ID:       3def84b9-c018-4145-af4d-4fb1c05cf243
:END:
我把org-mode的一份副本保留在 =git= 仓库 =~/git/org-mode/= 中。
这个克隆是用
#+begin_src sh
cd ~/git
git clone git://orgmode.org/org-mode.git
#+end_src

要更新和获取org-mode开发者的新commits，你可以使用
#+begin_src sh
cd ~/git/org-mode
git pull
make uncompiled
#+end_src

我在我的设置中运行未编译的源文件，所以未编译的make目标就是你需要的。

我通常使用org-mode仓库中的 =master= 分支。
** 4.2 org-mode的安装
在我的.emacs文件中的以下设置为大多数缓冲区启动了org-mode。org-mode是 =.org=, =.org_archive= 和 =.txt= 文件的默认mode。
#+begin_src emacs-lisp
;;;
;;; Org Mode
;;;
(add-to-list 'load-path (expand-file-name "~/git/org-mode/lisp"))
(add-to-list 'auto-mode-alist '("\\.\\(org\\|org_archive\\|txt\\)$" . org-mode))
(require 'org)
;;
;; Standard key bindings
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
#+end_src
这是你在org-mode中开始使用标题和列表所需要的一切。

本文的剩余部分描述了我在我的设置中使用的自定义功能，我是如何构建org-mode文件的,以及为适应我想org-mode去工作的方式而做出的其他改变。
** 4.3 把你的生活组织到org文件里

任务被分离成逻辑分组或项目。为大型任务分组使用单独的org文件，为属于多个项目的文件集合使用子目录。

以下是我使用的样本文件。

下面的org-文件收集了与工作无关的任务:

| 文件名       | 说明                         |
|--------------+------------------------------|
| todo.org     | 个人任务和需要保持跟踪的事情 |
| gsoc2009.org | 2009年谷歌编程之夏的事情     |
| farm.org     | 农场相关的任务               |
| mark.org     | 与我儿子Mark有关的任务       |
| org.org      | org-mode相关的任务           |
| git.org      | Git相关的任务                |

下面的org-file收集了org捕获的笔记和任务。

| 文件名     | 说明          |
|------------+---------------|
| refile.org | capture任务桶 |

以下与工作相关的org-文件保存了我的业务笔记（使用
虚构的客户名称)

| 文件名      | 描述                                 |
|-------------+--------------------------------------|
| norang.org  | norang任务和笔记                     |
| XYZ.org     | XYZ公司的任务和笔记                  |
| ABC.org     | ABC有限公司任务                      |
| ABC-DEF.org | ABC有限公司为其客户DEF公司的任务     |
| ABC-KKK.org | ABC有限公司为其客户KKK公司所做的任务 |
| YYY.org     | YYY Inc任务                          |

org-mode非常适合于处理多个客户和客户项目。
项目。 一个org文件成为单个客户或客户的项目、笔记等的集合。
等的集合，适用于单个客户或客户项目。

客户ABC有限公司有多个客户系统，我在上面工作。
将每个客户的任务分离到不同的组织文件中去
有助于保持事情的逻辑分组，由于客户来来去去，这
允许从我的议程中添加或删除整个组织文件，以保持
在议程视图中只显示重要的内容。

其他的org文件只用于发布，对议程没有贡献。
参见[[#发布][发布和导出]]了解更多细节。


